spring:
  application:
    name: cs203
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME:dev_user}   # Default value as fallback
    password: ${DB_PASSWORD}            # No default - forces setting env var
  jpa:
    show-sql: true