spring:
  application:
    name: cs203
  datasource:
#    url: jdbc:mysql://cs203db.cze64es4494n.ap-southeast-1.rds.amazonaws.com:3306/tariff
#    username: admin
#    password: CS203issofun
    url: jdbc:mysql://localhost:3306/tariff?createDatabaseIfNotExist=true
    username: root
    password: password123
  jpa:
    show-sql: true
  jwt:
    secret: ${JWT_SECRET}