spring:
  application:
    name: cs203
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}   # default profile
  main:
    allow-circular-references: true
  jwt:
    secret: ${JWT_SECRET}
    accessTokenExpiration: 3600 # 1 hour
    refreshTokenExpiration: 604800 # 7 days

# Common Logging Configuration
logging:
  level:
    root: INFO
    com.lynus.cs203: INFO
    org.springframework.security: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

server:
  port: ${PORT:8080}
  error:
    include-message: always